name: laboriq
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - pandas>=2.1.0
  - scikit-learn=1.3.2
  - matplotlib>=3.8.0
  - flask=3.0.0
  - wordcloud>=1.9.3
  - pip:
    - laiser>=0.3.0
